"""Add tier to Merchant

Revision ID: 2bdeb6bddfb0
Revises: 64fe5c1cbafe
Create Date: 2026-03-21 13:49:18.214412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bdeb6bddfb0'
down_revision: Union[str, None] = '64fe5c1cbafe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('merchants', sa.Column('tier', sa.String(length=32), nullable=True))
    op.execute("UPDATE merchants SET tier = 'BRONZE'")
    op.alter_column('merchants', 'tier', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('merchants', 'tier')
    # ### end Alembic commands ###
