"""add webhook logs

Revision ID: 36d9a395e0fa
Revises: 84355f811523
Create Date: 2026-03-21 13:04:24.690351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36d9a395e0fa'
down_revision: Union[str, None] = '84355f811523'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('webhook_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('response_status', sa.Integer(), nullable=True),
    sa.Column('response_body', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhook_logs_invoice_id'), 'webhook_logs', ['invoice_id'], unique=False)
    op.add_column('invoices', sa.Column('customer_email', sa.String(length=255), nullable=True))
    op.add_column('invoices', sa.Column('description', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_invoices_customer_email'), 'invoices', ['customer_email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invoices_customer_email'), table_name='invoices')
    op.drop_column('invoices', 'description')
    op.drop_column('invoices', 'customer_email')
    op.drop_index(op.f('ix_webhook_logs_invoice_id'), table_name='webhook_logs')
    op.drop_table('webhook_logs')
    # ### end Alembic commands ###
