"""add_usd_fields_to_models

Revision ID: 5fa8c84bea0d
Revises: 2bdeb6bddfb0
Create Date: 2026-03-21 14:05:33.165511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fa8c84bea0d'
down_revision: Union[str, None] = '2bdeb6bddfb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('amount_usd', sa.Numeric(precision=18, scale=2), nullable=True))
    op.add_column('system_fee_log', sa.Column('gross_amount_usd', sa.Numeric(precision=18, scale=2), nullable=True))
    op.add_column('system_fee_log', sa.Column('fee_amount_usd', sa.Numeric(precision=18, scale=2), nullable=True))
    op.add_column('system_fee_log', sa.Column('net_amount_usd', sa.Numeric(precision=18, scale=2), nullable=True))
    op.add_column('system_fee_log', sa.Column('usd_rate', sa.Numeric(precision=18, scale=2), nullable=True))
    op.add_column('transactions', sa.Column('amount_usd', sa.Numeric(precision=18, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'amount_usd')
    op.drop_column('system_fee_log', 'usd_rate')
    op.drop_column('system_fee_log', 'net_amount_usd')
    op.drop_column('system_fee_log', 'fee_amount_usd')
    op.drop_column('system_fee_log', 'gross_amount_usd')
    op.drop_column('invoices', 'amount_usd')
    # ### end Alembic commands ###
