"""Add User table for JWT auth

Revision ID: 64fe5c1cbafe
Revises: 36d9a395e0fa
Create Date: 2026-03-21 13:35:46.132207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '64fe5c1cbafe'
down_revision: Union[str, None] = '36d9a395e0fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'MERCHANT', name='user_role'), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.add_column('audit_logs', sa.Column('user_id', sa.UUID(), nullable=True))
    op.drop_index(op.f('ix_audit_logs_admin_id'), table_name='audit_logs')
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.drop_constraint(op.f('audit_logs_admin_id_fkey'), 'audit_logs', type_='foreignkey')
    op.create_foreign_key(None, 'audit_logs', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.drop_column('audit_logs', 'admin_id')

    op.drop_index(op.f('ix_admin_users_username'), table_name='admin_users')
    op.drop_table('admin_users')
    
    # Seed initial admin user
    import uuid
    admin_id = uuid.uuid4()
    op.execute(
        sa.text(
            "INSERT INTO users (id, email, hashed_password, role, is_active, created_at) "
            "VALUES (:id, :email, :password, CAST(:role AS user_role), true, now())"
        ).bindparams(
            id=admin_id,
            email='admin@nexuspay.com',
            password='$2b$12$O5998whnOiTu2KINHFAVGeuTqzYZ53iLSkyWl5mJuHOHtx.kdE/yy',
            role='ADMIN'
        )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('admin_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.create_foreign_key(op.f('audit_logs_admin_id_fkey'), 'audit_logs', 'admin_users', ['admin_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.create_index(op.f('ix_audit_logs_admin_id'), 'audit_logs', ['admin_id'], unique=False)
    op.drop_column('audit_logs', 'user_id')
    op.create_table('admin_users',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.Column('role', postgresql.ENUM('SUPERADMIN', 'SUPPORT', 'VIEWER', name='admin_role'), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('admin_users_pkey'))
    )
    op.create_index(op.f('ix_admin_users_username'), 'admin_users', ['username'], unique=True)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
