"""add merchant status

Revision ID: 84355f811523
Revises: ba3131d57f9a
Create Date: 2026-03-21 13:01:58.226632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84355f811523'
down_revision: Union[str, None] = 'ba3131d57f9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the enum type first
    merchant_status = sa.Enum('ACTIVE', 'PENDING', 'SUSPENDED', name='merchant_status')
    merchant_status.create(op.get_bind(), checkfirst=True)
    
    op.add_column('merchants', sa.Column('status', merchant_status, nullable=False, server_default='PENDING'))
    op.drop_index(op.f('ix_merchants_is_active'), table_name='merchants')
    op.create_index(op.f('ix_merchants_status'), 'merchants', ['status'], unique=False)
    op.drop_column('merchants', 'is_active')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('merchants', sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_merchants_status'), table_name='merchants')
    op.create_index(op.f('ix_merchants_is_active'), 'merchants', ['is_active'], unique=False)
    op.drop_column('merchants', 'status')
    # ### end Alembic commands ###
