"""add_merchant_name_email_note

Revision ID: 87d529aba417
Revises: 5fa8c84bea0d
Create Date: 2026-03-21 14:37:17.042828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87d529aba417'
down_revision: Union[str, None] = '5fa8c84bea0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('merchants', sa.Column('name', sa.String(length=255), nullable=True))
    op.add_column('merchants', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('merchants', sa.Column('note', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('merchants', 'note')
    op.drop_column('merchants', 'email')
    op.drop_column('merchants', 'name')
    # ### end Alembic commands ###
