"""add_country_code_to_invoice

Revision ID: f76d484a7c1e
Revises: 593e8b72d0f4
Create Date: 2026-03-21 17:49:23.630029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f76d484a7c1e'
down_revision: Union[str, None] = '593e8b72d0f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('country_code', sa.String(length=2), nullable=True))
    op.create_index(op.f('ix_invoices_country_code'), 'invoices', ['country_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invoices_country_code'), table_name='invoices')
    op.drop_column('invoices', 'country_code')
    # ### end Alembic commands ###
